name: Daily donate in 93589

on:
  workflow_dispatch: 
  schedule:
    - cron: '00 12 * * *'

jobs:
  dy_auto_donate_helper:
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout'
        uses: actions/checkout@v4
      - name: 'Set up Python'
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'
      - name: 'Install requirements'
        run: pip install -r requirements.txt
      - name: 'Working'
        env:
          SERVERPUSHKEY: ${{ secrets.SERVERPUSHKEY }}
          COOKIES: ${{ secrets.COOKIES }}
          BARKURL: ${{ secrets.BARKURL }}
        run: |
          python main.py
